name: 'SHFT PullMate'
description: 'A GitHub Action that checks if a pull request meets the requirements of the SHFT workflow'
author: 'SHFT'

inputs:
  reviewerRequired:
    description: 'Whether a reviewer is required or not'
    required: true
    default: 'true'
  assigneeRequired:
    description: 'Whether an asignee is required or not'
    required: true
    default: 'true'
  checklistRequired:
    description: 'Whether a checklist is required or not'
    required: true
    default: 'true'
  semanticTitleRequired:
    description: 'Whether a semantic title is required or not'
    required: true
    default: 'true'
  semanticBranchNameRequired:
    description: 'Whether a semantic branch name is required or not'
    required: true
    default: 'true'
  repoToken:
    description: 'The repository token'
    required: true

runs:
  using: node20
  main: dist/index.js
